// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmy0oxCpjEFDJ4xfSLukWF9A0Ez_Ibmo',
    appId: '1:188408037009:web:acf9173f1d5716dca74930',
    messagingSenderId: '188408037009',
    projectId: 'flutter-demo-2023',
    authDomain: 'flutter-demo-2023.firebaseapp.com',
    storageBucket: 'flutter-demo-2023.appspot.com',
    measurementId: 'G-FHWXS40GDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpT1klI9oXUKWft08AB4ZClAd9ZQA_OFE',
    appId: '1:188408037009:android:292968d32f6e714ea74930',
    messagingSenderId: '188408037009',
    projectId: 'flutter-demo-2023',
    storageBucket: 'flutter-demo-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaHZb9zMmfWCMvmdHx1Fi5RuwOlAH5YQ',
    appId: '1:188408037009:ios:015cf42e76fb1daea74930',
    messagingSenderId: '188408037009',
    projectId: 'flutter-demo-2023',
    storageBucket: 'flutter-demo-2023.appspot.com',
    iosClientId: '188408037009-q0mnj92hpen6bfi76dl4t77j2517l16e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaHZb9zMmfWCMvmdHx1Fi5RuwOlAH5YQ',
    appId: '1:188408037009:ios:015cf42e76fb1daea74930',
    messagingSenderId: '188408037009',
    projectId: 'flutter-demo-2023',
    storageBucket: 'flutter-demo-2023.appspot.com',
    iosClientId: '188408037009-q0mnj92hpen6bfi76dl4t77j2517l16e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
